<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="CoolTank" Id="{015173cf-e13a-4eb8-95d7-7cc655e5d0c5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CoolTank
VAR_INPUT
	refTank : REFERENCE TO St_Tank;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[reftank.temperature := refTank.temperature - 1;]]></ST>
    </Implementation>
    <LineIds Name="CoolTank">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>